server:
  port: 8080 #a port amelyen elered az alkalmazast

spring:  
  rabbitmq:
    host: 192.168.178.1
    port: 5672
    username: guest
    password: guest
   
  application:
    name: chat-service # Az alkalmazás neve

  security:
    user:
      name: emilia # Felhasználónév
      password: $2a$12$cEDcchID3ErUi3JbwscbbuUZBKr8NZCLYDS.Llf/9CiiTbpwepIQC # Jelszó

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # A MySQL driver osztálya
    url: jdbc:mysql://localhost:3306/tabla2?useSSL=false&allowPublicKeyRetrieval=true # A MySQL URL-je
    username: root # A MySQL felhasználóneve
    password: 50ReszeltAlma # A MySQL jelszava
    #password: qwertyui

  jpa:
    show-sql: true # A SQL lekérdezések megjelenítése
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect # A MySQL dialect-je
    hibernate:
      ddl-auto: update # A táblák létrehozása automatikusan történik

  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

logging:  
  level:
    root: info
